### ISSUE TITLE
mac OS 10.8-10.10 support

### ISSUE THREAD

**Issue by akissinger** [tikzit/tikzit#28]
Currently TikZiT only runs on mac OS 10.11 or later. This is because the travis-ci config I'm using to build pulls Qt 5.11 from homebrew.

In principle, TikZiT should still run on Qt 5.6, which seems to have support going back to 10.8, but it seems to be non-trivial to set up a travis-ci build to pull 5.6.

**Comment by zamdzhiev** [comment]
Are you sure it runs on Qt 5.6? I can't build it from source with Qt 5.7.1 on Debian Stable. The error which comes up is

`error: ‘class QTextEdit’ has no member named ‘setTabStopDistance’;`

According to the Qt documentation, [this was introduced in Qt 5.10.](http://doc.qt.io/qt-5/qtextedit.html#tabStopDistance-prop)

**Comment by akissinger** [comment]
I guess it will need some tweaking. That particular call replaces an older (deprecated) one, so it could be set conditionally in the constructor rather than in the .ui file. I don't think this process would be totally un-painful, so I might wait until a critical mass of people want it on older OSes before I invest too much time.

**Comment by akissinger** [comment]
tikzit now builds on Qt 5.6 or greater. (tested 5.6, 5.9, 5.10, and 5.11)

I've added a download link on the website for mac OS 10.8-10.10 users, which links to Qt 5.6 (the latest LTS version which has support for pre-10.10 versions of macOS). Currently this is not tested, because I don't have access to a mac running an old version of macOS.

**Comment by zamdzhiev** [comment]
Awesome! I can build it and run it with Qt 5.7, so it looks like it can be build pretty much on anything now.
